# Generated by Django 3.0 on 2019-12-12 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DatosPersonales',
            new_name='DatosPersonale',
        ),
    ]
