# Generated by Django 3.0 on 2019-12-12 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0002_auto_20191212_1809'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DatosPersonale',
            new_name='DatosPersonales',
        ),
    ]
