# Generated by Django 3.0 on 2019-12-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0003_auto_20191212_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='Num_count',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
